package model.frame;

public class Sql {
	//customer
	public static String insertCust = "INSERT INTO CUSTOMER VALUES (?,?,?,?,?,?)";
	public static String updateCust = "UPDATE CUSTOMER SET PWD=? , NAME=?, GENDER=?, AGE=?, LOCATION=? WHERE ID= ?";//회원정보수정 나중에
	public static String selectCust ="SELECT * FROM CUSTOMER WHERE ID = ?";
	public static String deleteCust = "DELETE FROM CUSTOMER WHERE ID = ?";

	//account
	public static String checkAcc = "SELECT COUNT(*) FROM ACCOUNT WHERE AID= ?"; 
	public static String insertAcc = "INSERT INTO ACCOUNT VALUES(?,?,?,?)";//USER가 잔액입력한경우	
	public static String selectAccount = "SELECT * FROM ACCOUNT WHERE AID=?";
	public static String updateAcc="UPDATE ACCOUNT SET ACCOUNTNUMBER =?,BANKNAME=?BALANCE =? WHERE AID=?";
	public static String deleteAcc = "DELETE FROM ACCOUNT WHERE ACCNO=?";
	public static String selectAllAcc = "SELECT ACCNO, BANKNAME, BALANCE FROM ACCOUNT WHERE AID=?";
	//0318 수정부분 (잔액조정)
	   public static String selectAccInfo = "SELECT ACCNO, BANKNAME, BALANCE FROM ACCOUNT WHERE ACCNO = ?";
	   public static String updateAccBalance = "UPDATE ACCOUNT SET balance = ? WHERE accno = ?";
	
	//public static String selectAcc = "SELECT ACCOUNTNUMBER FROM ACCOUNT WHERE AID =?";
	//db 서버 변수 확인할것.
	
	
	//HISTORY 	
	public static String selectAllSeq="SELECT * FROM HISTORY WHERE HIS_SEQ = ?";   
	   
	public static String insertHis ="INSERT INTO HISTORY VALUES(HIS_SEQ.NEXTVAL, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	public static String selectAcc = "SELECT ACCOUNTNUMBER FROM ACCOUNT WHERE AID =?";
	public static String deleteHis="DELETE FROM HISTORY WHERE HIS_SEQ=?";
	public static String selectDWCode="SELECT HIS_SEQ, HACCNO, BANKNAME, DWCODE, PAYTYPE, PRICE, HDATE, MEMO, SPECIFICATION, HMCODE, AID, MCODENAME , LCODENAME FROM HISTORY H, ACCOUNT A, MCATEGORY M ,LCATEGORY L WHERE H.HACCNO=A.ACCNO AND M.MCODE=H.HMCODE AND M.MLCODE=L.LCODE AND AID = ? AND DWCODE= ?";
	//id에 해당하는 모든 계좌, 모든 his 출력 sql
	public static String selectAllHis="SELECT HIS_SEQ, HACCNO, BANKNAME, DWCODE, PAYTYPE, PRICE, HDATE, MEMO, SPECIFICATION, HMCODE, AID, MCODENAME , LCODENAME FROM HISTORY H, ACCOUNT A, MCATEGORY M ,LCATEGORY L WHERE H.HACCNO=A.ACCNO AND M.MCODE=H.HMCODE AND M.MLCODE=L.LCODE AND AID = ?";

	//계좌별조회
	public static String selectacchis="SELECT HIS_SEQ, HACCNO, BANKNAME, DWCODE, PAYTYPE, PRICE, HDATE, MEMO, SPECIFICATION, HMCODE, AID, MCODENAME FROM HISTORY H, ACCOUNT A, MCATEGORY M WHERE H.HACCNO=A.ACCNO AND M.MCODE=H.HMCODE AND HACCNO = ?";
	
	//조건붙인조회들
	public static String selectDate="SELECT HIS_SEQ, HACCNO, BANKNAME, DWCODE, PAYTYPE, PRICE, HDATE, MEMO, SPECIFICATION, HMCODE, AID, MCODENAME FROM HISTORY H, ACCOUNT A, MCATEGORY M WHERE H.HACCNO=A.ACCNO AND M.MCODE=H.HMCODE AND HDATE BETWEEN ? AND ? AND AID = ?";
	public static String selectHaccNO="SELECT HACCNO ,DWCODE,PAYTYPE, PRICE, HDATE,MEMO,SPECIFICATION ,HMCODE  FROM HISTORY  WHERE HACCNO = ?";
	//public static String selectTop="SELECT HACCNO ,DWCODE,PAYTYPE, PRICE, HDATE,MEMO,SPECIFICATION ,HMCODE FROM (SELECT *FROM HISTORYORDER BY HDATE DESC) WHERE ROWNUM < 30";
	//public static String selectOMon="SELECT HACCNO ,DWCODE,PAYTYPE, PRICE, HDATE,MEMO,SPECIFICATION ,HMCODE FROM HISTORY WHERE HDATE BETWEEN SYSDATE-30 AND SYSDATE";
	//public static String selectTMon="SELECT HACCNO ,DWCODE,PAYTYPE, PRICE, HDATE,MEMO,SPECIFICATION ,HMCODE FROM HISTORY WHERE HDATE BETWEEN SYSDATE-60 AND SYSDATE";
	//public static String selectSMon="SELECT HACCNO ,DWCODE,PAYTYPE, PRICE, HDATE,MEMO,SPECIFICATION ,HMCODE FROM HISTORY WHERE HDATE BETWEEN SYSDATE-90 AND SYSDATE";


	//MCATEGORY
	public static String selectMcategory="SELECT * FROM MCATEGORY WHERE MLCODE=? ORDER BY MCODE";
	
	//LCATEGORY
	public static String selectLcategory="SELECT * FROM LCATEGORY ORDER BY LCODE";
}